
@file:JvmName("FindTheDifferenceKt")

import org.junit.*

/**
 * Solution
 * ---
 * Given two strings **_s_** and **_t_** which consist of only lowercase letters.
 * 
 * String **_t_** is generated by random shuffling string **_s_** and then add
 * one more letter at a random position.
 * 
 * Find the letter that was added in **_t_**.
 * 
 * **Example:**
 * 
 * [Subscribe](/subscribe/) to see which companies asked this question.
 * 
 * 
 */
fun findTheDifference() {

}

/**
 * Tests
 */
class FindTheDifferenceTest {
    @Test fun test1() {

    }

    @Test fun test2() {

    }
}

